site_name: ffortier's github page
site_url: https://ffortier.github.io/mono
repo_url: https://github.com/ffortier/mono
nav:
  - Intro: index.md
  - Experiments: "*include ./experiments/*/mkdocs.yml"
  - Modules: "*include ./modules/*/mkdocs.yml"

theme: material

plugins:
  - monorepo

extra_javascript:
  - script/hello.js
  - script/nb.js
  - script/digital.js
  - script/gol64.js
  - script/quest64_tiles.js

extra_css:
  - styles/nb.css
